spap/interface/urls.py
from django.conf.urls import url,include
from .views import *

urlpatterns = [
    url(r'^$',UserFormView.as_view(),name="login"),
    url(r'^logOut$',LogOut.as_view(),name="logOut"),
    url(r'^dashboard/$',DashboardView.as_view(),name="dashboard"),
    url(r'^dashboard/usersactivity/(?P<activity>[\w-]+)/$',UserActivity.as_view(),name="useractivity"),
    url(r'^dashboard/species/(?P<bodytype>[\w-]+)/(?P<bodyId>[\d-]+)/$',SpeciesInfo.as_view(),name="species"),
    url(r'^dashboard/downloadCsvFile$',DownloadCsvFile.as_view(),name="downloadCsvFile"),
    url(r'^dashboard/sendnotification$',SendNotification.as_view(),name="sendNotification"),
    url(r'^dashboard/forest/beat/(?P<beatId>[\d-]+)/(?P<plantType>[\w-]+)/$',BeatInfo.as_view(),name="beatInfo"),
    url(r'^dashboard/forest/range/(?P<rangeId>[\d-]+)/(?P<plantType>[\w-]+)/$',RangeInfo.as_view(),name="rangeInfo"),
    url(r'^dashboard/forest/division/(?P<divisionId>[\d-]+)/(?P<plantType>[\w-]+)/$',DivisionInfo.as_view(),name="divisionInfo"),
    url(r'^dashboard/forest/detail/(?P<plantId>[\d]+)/$',DetailInfoPlants.as_view(),name="detailInfoPlants"),
]

spap/spap/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url,include
from rest_framework.authtoken import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^', include("interface.urls",namespace="interface")),
    url(r'^admin/', admin.site.urls),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^users/', include('users.urls')),
    url(r'^departments/', include('departments.urls')),
    url(r'^media/', include('media.urls')),
    url(r'^regspecies/', include('regspecies.urls')),
    url(r'^speciesdata/', include('speciesdata.urls')),
    url(r'^resourcetransaction/', include('resourcetransaction.urls')),

] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spap/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Forest Friend - {% block title %} {% endblock%} | NIT SILCHAR</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'interface/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{% static 'interface/css/jquery-jvectormap-1.2.2.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'interface/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'interface/css/_all-skins.min.css' %}">
  {% block page_css %} {% endblock %}
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    {% include "header.html" %}
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    {% include "sidebar.html" %}
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Forest Friend
        <small>Version 1.1</small>
      </h1>
    </section>

    {% block main_content %}
    {% endblock %}
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    {% include "footer.html" %}
  </footer>


  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'interface/js/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'interface/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'interface/js/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'interface/js/app.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'interface/js/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'interface/js/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'interface/js/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- SlimScroll 1.3.0 -->
<script src="{% static 'interface/js/jquery.slimscroll.min.js' %}"></script>
<!-- ChartJS 1.0.1 -->
<script src="{% static 'interface/js/Chart.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="{% static 'interface/js/dashboard2.js' %}"></script> -->
<!-- AdminLTE for demo purposes -->
<script src="{% static 'interface/js/demo.js' %}"></script>
{% block page_js %} {% endblock %}
</body>
</html>

spap/templates/dashboard.html
{% extends "base.html" %}
{% block title %} Dashboard {% endblock%}
{% block main_content %}
    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <a href="{% url 'interface:useractivity' activity='active' %}">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion-android-happy"></i></span>

            <div class="info-box-content">
              <span class="info-box-text"> Active Users </span>
              <span class="info-box-number">{{ total_active_users }}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div> </a>

        <!-- /.col -->
        <a href="{% url 'interface:useractivity' activity='inactive' %}">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-red"><i class="ion-android-sad"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Inactive Users</span>
              <span class="info-box-number">{{ total_inactive_users }}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div> </a>
        <!-- /.col -->

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>

        <!-- /.col -->
        <!-- /.col -->
      </div>
      <!-- /.row -->
      <!-- /.row -->

      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <div class="col-md-8">
          <!-- MAP & BOX PANE -->
          <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">CACHAR MAP</h3>

              <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <div id="world-map-markers" style="height: 325px; margin-left: 20px; margin-right: 20px;"></div>
              <!-- /.row -->
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
          <!-- /.box -->
        </div>
        <!-- /.col -->


        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>

{% endblock %}    

{% block page_js %}
  <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('world-map-markers'), {
          center: {lat: 24.8333, lng: 92.7789},
          zoom: 8
        });
      }
    </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAteM4P82ZpVfZHUA-greFhVVphVI9UcI0&callback=initMap"
    async defer></script>
{% endblock %}

spap/templates/detailViewOfPlant.html
{% extends "base.html" %}
{% load staticfiles %}
{% block main_content %}
<div class="row" style="margin:0.5%;">
  <div class="col-xs-12">
    <div class="box box-primary" >
      <div class="box-header with-border">
        <h3 class="box-title">Details of Plant</h3>
      </div>
      <div class="box-body">
        <div class="col-sm-8">
          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>Scientfic Name</b> <a class="pull-right">{{ obj.plantae.scientific_name }}</a>
            </li>
            <li class="list-group-item">
              <b>State</b> <a class="pull-right">{{ obj.state }}</a>
            </li>
            <li class="list-group-item">
              <b>District</b> <a class="pull-right">{{ obj.district }}</a>
            </li>
            <li class="list-group-item">
              <b>Latitude</b> <a class="pull-right">{{ obj.latitude }}</a>
            </li>
            <li class="list-group-item">
              <b>Longitude</b> <a class="pull-right">{{ obj.longitude }}</a>
            </li>
            {% if obj.ptype == "SB" %}
            <li class="list-group-item">
              <b>Plant Type</b> <a class="pull-right">Seed Bearing</a>
            </li>
            {% elif obj.ptype == "IG"%}
              <li class="list-group-item">
                <b>Plant Type</b> <a class="pull-right">Ingeneous tree</a>
              </li>            
            {% else %}
              <li class="list-group-item">
                <b>Plant Type</b> <a class="pull-right">Indegenous patch</a>
              </li>
            {% endif %}
            <li class="list-group-item">
              <b>Patch</b> <a class="pull-right">{{ obj.patch }}</a>
            </li>
          </ul>
        </div>
        <div class="col-sm-4">
          <img class="img-responsive" src="{{ obj.images.image1.url }}">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

spap/templates/footer.html
{% load staticfiles %}
<div class="pull-right hidden-xs">
      <b>Version</b> 1.1
    </div>
    <strong>Copyright &copy; 2016 <a href="http://nits.ac.in" target="_blank">NIT SILCHAR</a>.</strong> All rights
    reserved.

spap/templates/header.html
{% load staticfiles %}
<!-- Logo -->
    <a href="{% url 'interface:dashboard' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">SPAP</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">SPAP</span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning"></span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                      page and may cause design problems
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-red"></i> 5 new members joined
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-user text-red"></i> You changed your username
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'interface/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{% static 'interface/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  {{ request.user.username }}
                  <small>Member since Nov. 2016</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                  <a href="{% url 'interface:logOut'%}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        </ul>
      </div>

    </nav>

spap/templates/login.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Forest Friend - LOGIN | NIT SILCHAR</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href="{% static 'interface/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'interface/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
 
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style>
  .help-block{
    display: none;
  }
  </style>
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>Forest Friend</b></a>
  </div>
  <!-- /.login-logo -->
{% if auth_failed %}  
 <div class="callout callout-danger">
    <h4>Authentication Failed!</h4>
    <p>Please enter correct username and password.</p>
  </div>
{% endif %} 
  <div class="login-box-body">
    <center><a href="http://www.nits.ac.in" target="_blank"><img src="{% static 'interface/img/nitslogo.png' %}" height="100px" width="105px"></a></center>
      <form method="POST" action=" " enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary btn-block btn-flat" type="submit" value="Log In">
    </form>
    <br>
    <p style="text-align:center">Developed By <a href="http://www.nits.ac.in" target="_blank">NIT Silchar</p> 
</div>
<!-- /.login-box -->

<!-- jQuery 2.2.3 -->
<script src="{% static 'interface/js/jquery-2.2.3.min.js' %}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{% static 'interface/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
</body>
</html>

spap/templates/loginForm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %} Toddler | login {% endblock %}

{% block content %}

	<div class="col-sm-3 col-sm-offset-4">
		<form method="POST" action=" " enctype="multipart/form-data">{% csrf_token %}
		{{ form|crispy }}
		<input class="btn btn-primary btn-block btn-flat" type="submit" value="Log In">
		</form>
		<p style="text-align:center">Developed By</p> 
		NIT Silchar

	</div>
{% endblock %}

spap/templates/registeredPlants.html
{% extends "base.html" %}
{% load staticfiles %}
{% block main_content %}
<section class="content">
<div class="box">
    <div class="box-header">
        <h3 class="box-title">Region wise registered plant data</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <div class="row">
               <div class="col-sm-4">
                  <div class="dataTables_length" id="example1_length">
                     <label>
                        {{ department }} 
                        <select name="example1_length" aria-controls="example1" class="form-control input-sm">
                           {% for list in idList %}
                                       <option value="{{ list.pk }}"> {{ list }}</option>
                           {% endfor%}
                        </select>
                     </label>
                  </div>
               </div>
               <div class="col-sm-3">
                  <div class="dataTables_length" id="example1_length">
                     <label>
                        <select name="example1_length" aria-controls="example1" class="form-control input-sm">
                                <option value="SB">Seed Bearing</option>
                                <option value="25">Indegenous Tree</option>
                                <option value="50">Ingeneous Patch</option>
                        </select>
                     </label>
                  </div>
               </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending" style="width: 181px;">Species Scientifc Name</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending" style="width: 224px;">State</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending" style="width: 198px;">District</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" style="width: 155px;">Latitude</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">Longitude</th>
                                <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending" style="width: 112px;">Patch</th>
                            </tr>
                        </thead>
                        <tbody>
                           {% for obj in queryset %}                                
                                 <tr role="row"> 
                                 <td><a href="{% url 'interface:detailInfoPlants' obj.regplantae  %}">
                                 {{ obj.plantae.scientific_name }} </a> </td> 
                                 <td>{{ obj.state }}</td>
                                 <td> {{ obj.district }}</td>
                                 <td> {{ obj.latitude }}</td>
                                 <td> {{ obj.longitude }}</td>
                                 <td> {{ obj.patch }}</td>
                                 
                                 </tr>
                          {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5" style="margin-top:30px">
                  <span class="current">
                  Showing Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                  </span>
               </div>
               <div class="col-sm-7">
                  <div class="dataTables_paginate paging_simple_numbers">
                     <ul class="pagination" style="float:right;">
                        {% if page_obj.has_previous %}
                        <li class="paginate_button previous" id="example1_previous">
                           <a href="?page={{ page_obj.previous_page_number }}" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a>
                        </li>
                        {% else %}
                        <li class="paginate_button previous disabled" id="example1_previous">
                           <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a>
                        </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                        <li class="paginate_button next" id="example1_next">
                           <a href="?page={{ page_obj.next_page_number }}" aria-controls="example1" data-dt-idx="1" tabindex="0">Next</a>
                        </li>
                        {% else %}
                        <li class="paginate_button next disabled" id="example1_next">
                           <a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0">Next</a>
                        </li>
                        {% endif %}
                     </ul>
                  </div>
               </div>
            </div>
        </div>
    </div>
</div>
</section>
{% endblock%}

spap/templates/sidebar.html
{% load staticfiles %}
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'interface/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ request.user.username}}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Seed Deposits</span>
            <span class="pull-right-container">
              <i class="fa fa-a ngle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'interface:species' bodytype='range' bodyId='1'%}"><i class="fa fa-circle-o"></i> Range</a></li>
            <li><a href="{% url 'interface:species' bodytype='beat' bodyId='1' %}"><i class="fa fa-circle-o"></i> Beat </a></li>
            <li class="active"><a href="{% url 'interface:species' bodytype='division' bodyId='1'%}"><i class="fa fa-circle-o"></i> Division </a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Forests</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li>
              <a href="{% url 'interface:divisionInfo' divisionId='1' plantType='SB'%}"><i class="fa fa-circle-o"></i> Division
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'interface:rangeInfo' rangeId='1' plantType='SB'%}"><i class="fa fa-circle-o"></i> Range
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'interface:beatInfo' beatId='1' plantType='SB'%}"><i class="fa fa-circle-o"></i> Beat
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->

spap/templates/userActivity.html
{% extends "base.html" %}
{% load staticfiles %}
{% block main_content %}
<section class="content">
   <div class="row">
      <div class="col-xs-12">
         <div class="box">
            <div class="box-header">
               <h3 class="box-title">{{ table_heading }} <small>In last 24 hours</small></h3>
               {% if inactive == True %}
              <a href="{% url 'interface:sendNotification' %}"><div class="btn btn-danger" style="float:right;margin-right:2%;"> Send sms</div> </a>
              {% endif %}
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               <table id="example1" class="table table-bordered table-striped">
                  <thead>
                     <tr>
                        <th>User Id</th>
                        <th>Name</th>
                        <th>Date</th>
                        <th>Time</th>
                     </tr>
                  </thead>
                  <tbody>
                     {% for obj in object_list%}
                     <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.user }}</td>
                        <td>{{ obj.last_activity|date }}</td>
                        <td> {{ obj.last_activity|time }}</td>
                     </tr>
                     {% endfor %} 
                  </tbody>
               </table>
               <div class="col-sm-5" style="margin-top:30px">
                  <span class="current">
                  Showing Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                  </span>
               </div>
               <div class="col-sm-7">
                  <div class="dataTables_paginate paging_simple_numbers">
                     <ul class="pagination" style="float:right;">
                        {% if object_list.has_previous %}
                        <li class="paginate_button previous" id="example1_previous">
                           <a href="?page={{ object_list.previous_page_number }}" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a>
                        </li>
                        {% else %}
                        <li class="paginate_button previous disabled" id="example1_previous">
                           <a href="#" aria-controls="example1" data-dt-idx="0" tabindex="0">Previous</a>
                        </li>
                        {% endif %}
                        {% if object_list.has_next %}
                        <li class="paginate_button next" id="example1_next">
                           <a href="?page={{ object_list.next_page_number }}" aria-controls="example1" data-dt-idx="1" tabindex="0">Next</a>
                        </li>
                        {% else %}
                        <li class="paginate_button next disabled" id="example1_next">
                           <a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0">Next</a>
                        </li>
                        {% endif %}
                     </ul>
                  </div>
               </div>
            </div>
            <!-- /.box-body -->
         </div>
      </div>
   </div>
</section>
{% endblock%}